services:
    
    app:
        container_name: simple-wallet-backend
        build:
            context: .
            dockerfile: Dockerfile
        image: thedavidinyang/simple-wallet-backend:latest
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www

        ports:
            - "5000:8080"

        depends_on:
            - db
        networks:
            - laravel
        command: php-fpm


    db:
      image: postgres:15
      container_name: postgres_db
      restart: unless-stopped
      environment:
        POSTGRES_DB: laravel
        POSTGRES_USER: laravel
        POSTGRES_PASSWORD: secret
      volumes:
        - pgdata:/var/lib/postgresql/data
      ports:
      - 5433:5432
      networks:
      - laravel

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - 9000:4000
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
        - laravel

volumes:
    pgdata:

networks:
    laravel:
        driver: bridge
