services:
  backend:
    container_name: simple-wallet-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: your-dockerhub-username/laravel-app:latest
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www

    ports:
      - "8080:8080"

    depends_on:
      - db
    networks:
      - laravel
    command: bash -c "supervisord -c /etc/supervisor/conf.d/supervisord.conf && php-fpm"
    # volumes:
    #   - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf